import type { WorkspacePrimitiveComponent } from "./shared";
import { asArray, asBulletText, asNumber, asRecord, asString, Badge } from "./shared";

export const Tabs: WorkspacePrimitiveComponent = ({ node }) => {
  const bind = asRecord(node.bind);
  const artifact = asRecord(bind.artifact ?? bind.record ?? bind.entity);
  const sections = asArray(artifact.sections);
  const tabs = Array.isArray(node.tabs) ? node.tabs : [];
  const verdict = asString(artifact.verdict ?? artifact.status);

  return (
    <section className="workspace-document">
      <header className="workspace-document__header">
        <div>
          <p className="workspace-document__eyebrow">Sections</p>
          <h2 className="workspace-document__section-title">{asString(artifact.title, "Document")}</h2>
          <p className="workspace-muted">
            Generated by {asString(artifact.generatedBy)} · {asString(artifact.generatedAt)}
          </p>
        </div>
        <div className="workspace-document__header-meta">
          <strong className="workspace-score">{asNumber(artifact.score)}</strong>
          {verdict ? <Badge label={verdict} /> : null}
        </div>
      </header>
      {tabs.length > 0 ? (
        <div className="workspace-tabs">
          {tabs.map((tab, index) => (
            <span className={`workspace-tab ${index === 0 ? "is-active" : ""}`.trim()} key={tab}>
              {tab.split("-").join(" ")}
            </span>
          ))}
        </div>
      ) : null}
      <div className="workspace-document__sections">
        {sections.map((section, index) => {
          const entry = asRecord(section);
          const bullets = asArray(entry.bullets);

          return (
            <article className="workspace-document__section" key={`${asString(entry.title)}-${index}`}>
              <h3>{asString(entry.title)}</h3>
              {entry.body ? <p>{asString(entry.body)}</p> : null}
              {bullets.length > 0 ? (
                <ul>
                  {bullets.map((bullet, bulletIndex) => (
                    <li key={`${bulletIndex}-${asBulletText(bullet)}`}>{asBulletText(bullet)}</li>
                  ))}
                </ul>
              ) : null}
            </article>
          );
        })}
      </div>
    </section>
  );
};
